DROP DATABASE IF EXISTS budget_tracker_db;

CREATE DATABASE budget_tracker_db;

USE budget_tracker_db;

CREATE TABLE users (
id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
email VARCHAR(100),
password VARCHAR(50)
);

CREATE TABLE income (
id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
amount INTEGER NOT NULL,
description VARCHAR(100) NOT NULL,
day DATE
);

CREATE TABLE expense (
id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
amount INTEGER NOT NULL,
description VARCHAR(100) NOT NULL,
day DATE 
);
